### ISSUE TITLE
Groups API

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/hue-api#5]
As far as I know, the groups API is a bit unstable when controlling newly created groups. People have had success by creating a group and then rebooting the base station. Apart from that, groups work nicely.

Even groups have a delay when sending out commands to individual lights though; something imposed by Zigbee protocol, or so.

**Comment by mperrin** [comment]
I have a suggested addition for the Groups API documentation: There appears to be a hidden group 0 which contains all the lights. (Presumably this is part of the 'All off' mechanism in the official apps? )

This doesn't show up if you list the /groups/ directory, but you can access it by explicitly requesting e.g.

```
GET /api/username/groups/0
```

``` python
{'action': {'bri': 240,
  'colormode': u'ct',
  'ct': 500,
  'effect': u'none',
  'hue': 0,
  'on': True,
  'sat': 250,
  'xy': [0.6704, 0.3229]},
 'lights': ['1', '2', '3', '4', '5', '6'],
 'name': 'Lightset 0'}
```

I've tested this out and I can command all lights to switch near-simultaneously to a given setting by commanding this group. (I only have 6 lamps for now so I can't yet stress test how simultaneous this really is; I expect it's not perfect).

**Comment by Burgestrand** [comment]
Oh yes, I’ve completely forgotten about the group 0! It’ll be a while before I’ll be able to make the effort of sitting myself down and writing it though; you’re very welcome to give it a go and send a pull request for this, and I’ll merge it in.

**Comment by Burgestrand** [comment]
I’ve added what I know about controlling a single group (and, in effect, group 0 too, with some additional information about it). There’s still details about creating and destroying a group, and the current status of how to get new groups work properly.

**Comment by Burgestrand** [comment]
Now that there’s official documentation, this is not very interesting. Closing the issue.
